on: [push, pull_request]
name: Tests and linters
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go Version
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'

      - name: Check Go Version
        run: go version

      - name: Run Go unit tests
        run: make test
